# Generated by Django 3.1.6 on 2021-04-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20210409_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidadproducto',
            name='ofertaProductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.ofertaproductor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='productoCatalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.productocatalogo'),
        ),
    ]
