# Generated by Django 3.1.6 on 2021-06-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductorPostulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFinca', models.CharField(max_length=1000)),
                ('nombre', models.CharField(max_length=1000)),
                ('correo', models.EmailField(max_length=1000)),
                ('celular', models.CharField(max_length=1000)),
                ('telefono', models.CharField(max_length=1000)),
                ('productos', models.CharField(max_length=1000)),
                ('cultivos', models.CharField(max_length=1000)),
                ('procesos', models.CharField(max_length=1000)),
                ('vereda', models.CharField(max_length=1000)),
                ('municipio', models.CharField(max_length=1000)),
                ('aceptado', models.BooleanField(default=False)),
            ],
        ),
    ]
