# Generated by Django 3.1.6 on 2021-04-09 01:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantidadProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('oferta_productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.ofertaproductor')),
            ],
        ),
    ]
